model:
  name: claude_37_sonnet
  class_path: starflow.model.vl_api_models.openrouter.OpenRouterAPIModel
  init_kwargs:
    base_url: https://openrouter.ai/api/v1
    model_id: anthropic/claude-3.7-sonnet
  chunk_size: 128
  generate_kwargs:
    max_tokens: 8192
    temperature: 0.0
