model:
  name: deepseek_vl2_tiny
  class_path: starflow.model.deepseek_vl2.DeepseekModel
  init_kwargs:
    model_path: deepseek-ai/deepseek-vl2-tiny
    torch_dtype: bfloat16
    ignore_index: -100
    max_length: 8192
    requires_grad_kwargs:
      language_model_requires_grad: true
      vision_model_requires_grad: true
      connector_requires_grad: true
    generate_kwargs:
      max_new_tokens: 8192
      do_sample: false
