model:
  name: gpt_4o
  class_path: starflow.model.vl_api_models.openrouter.OpenRouterAPIModel
  init_kwargs:
    base_url: https://openrouter.ai/api/v1
    model_id: openai/gpt-4o-2024-11-20
  chunk_size: 128
  generate_kwargs:
    max_tokens: 8192
    temperature: 0.0
