model:
  name: llama_32_11b
  class_path: starflow.model.vl_models.llama32.LlamaModel
  init_kwargs:
    pretrained_model_path: meta-llama/Llama-3.2-11B-Vision-Instruct
    torch_dtype: bfloat16
    ignore_index: -100
    max_length: 8192
    max_new_tokens: 8192
  source_logging_dir: null
  requires_grad_kwargs:
    language_model_requires_grad: true
    vision_model_requires_grad: true
    connector_requires_grad: true
  generate_kwargs:
    do_sample: false
