model:
  name: phi_4_6b
  class_path: starflow.model.vl_models.phi.PhiModel
  init_kwargs:
    pretrained_model_path: microsoft/Phi-4-multimodal-instruct
    torch_dtype: bfloat16
    attn_implementation: flash_attention_2
    ignore_index: -100
    max_length: 8192
    max_new_tokens: 8192
  source_logging_dir: null
  train_language_model: true
  train_vision_model: true
  train_connector: true
  generate_kwargs:
    do_sample: false
