model:
  name: pixtral_12b
  class_path: starflow.model.pixtral.PixtralModel
  init_kwargs:
    model_path: mistral-community/pixtral-12b
    torch_dtype: bfloat16
    ignore_index: -100
    max_length: 8192
    requires_grad_kwargs:
      language_model_requires_grad: true
      vision_model_requires_grad: true
      connector_requires_grad: true
    generate_kwargs:
      max_new_tokens: 8192
      do_sample: false
