model:
  name: qwen_25_vl_7b
  class_path: starflow.model.vl_models.qwen25.QwenModel
  init_kwargs:
    pretrained_model_path: Qwen/Qwen2.5-VL-7B-Instruct
    torch_dtype: bfloat16
    attn_implementation: flash_attention_2
    ignore_index: -100
    max_length: 8192
    max_new_tokens: 8192
  source_logging_dir: null
  requires_grad_kwargs:
    language_model_requires_grad: true
    vision_model_requires_grad: true
    connector_requires_grad: true
  generate_kwargs:
    do_sample: false
