model:
  name: qwen_25_vl_32b
  class_path: starflow.model.qwen_25.QwenModel
  init_kwargs:
    model_path: Qwen/Qwen2.5-VL-32B-Instruct
    torch_dtype: bfloat16
    attn_implementation: flash_attention_2
    ignore_index: -100
    max_length: 8192
    requires_grad_kwargs:
      language_model_requires_grad: true
      vision_model_requires_grad: true
      connector_requires_grad: true
    generate_kwargs:
      max_new_tokens: 8192
      do_sample: false
