model:
  name: vllm_qwen_25_vl_7b
  class_path: starflow.model.openai.OpenAIModel
  init_kwargs:
    base_url: http://localhost:8000/v1
    model_path: Qwen/Qwen2.5-VL-7B-Instruct
    generate_kwargs:
      max_tokens: 8192
      temperature: 0.0
